<a href="https://colab.research.google.com/github/DGluszyk/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install numpy

In [3]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
help(np.array)

In [8]:
x = np.array([1, 3])
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

In [10]:
x.ndim

1

In [11]:
x.shape

(2,)

In [12]:
x.size

2

In [14]:
x.dtype

dtype('int64')

In [17]:
x=np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [18]:
x.dtype

dtype('float64')

In [21]:
x = np.array([[1, 2], [-3, 1]])

In [22]:
x.ndim

2

In [23]:
x.shape

(2, 2)

In [25]:
x = np.array([[1,2,4], [5, 6, 8]])
print(x)

[[1 2 4]
 [5 6 8]]


In [26]:
x.shape

(2, 3)

In [32]:
x = np.array(
    [[[4,1,2],
      [5, 6, 7]],

      [[4, 2, 3],
       [2, 3, 9]],

     [[4, 7, 9],
      [3, 6, 5]]]
)

x

array([[[4, 1, 2],
        [5, 6, 7]],

       [[4, 2, 3],
        [2, 3, 9]],

       [[4, 7, 9],
        [3, 6, 5]]])

In [33]:
x.ndim

3

In [34]:
x.shape

(3, 2, 3)

### Typy danych

In [36]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [38]:
A = np.array([1.3, 2.2, 3.1])


dtype('float64')

In [41]:
A = np.array([1, 2, 3], dtype = 'complex')
print(A.dtype)
A

complex128


array([1.+0.j, 2.+0.j, 3.+0.j])

In [42]:
A = np.array([1.4, 2.2, 3.9], dtype = 'int')
print(A.dtype)
A

int64


array([1, 2, 3])

In [43]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [49]:
A = np.array([24, 120, 250], dtype=np.uint8)
A.dtype

dtype('uint8')

### Tworzenie tablic

In [50]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
np.zeros(shape=(4, 10), dtype='int')


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [53]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [55]:
np.full(shape=(3, 3), fill_value=5, dtype='int')

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [57]:
np.arange(10)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [58]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [60]:
np.arange(start=10, stop=100, step = 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
np.arange(start=100, stop=10, step = -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [62]:
np.arange(start=0, stop=1, step = 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [64]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.arange(start=0)

In [66]:
A = np.arange(15)

In [67]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Podstawowe operacje

In [76]:
A = np.array([3, 5, 6, 7])
B = np.array([1, 2, 3, 4])
print(A)
print(B)

[3 5 6 7]
[1 2 3 4]


In [71]:
A + B

array([ 4,  7,  9, 11])

In [72]:
A - B

array([2, 3, 3, 3])

In [73]:
A * B

array([ 3, 10, 18, 28])

In [74]:
A / B

array([3.  , 2.5 , 2.  , 1.75])

In [77]:
A + 3

array([ 6,  8,  9, 10])

In [78]:
2 * A

array([ 6, 10, 12, 14])

In [79]:
A + 3 *B

array([ 6, 11, 15, 19])

In [80]:
np.add(A, B)

array([ 4,  7,  9, 11])

In [81]:
np.subtract(A, B)

array([2, 3, 3, 3])

In [82]:
np.multiply(A, B)

array([ 3, 10, 18, 28])

In [83]:
np.divide(A, B)

array([3.  , 2.5 , 2.  , 1.75])

In [86]:
X = np.array([[1, 2], [3, 4]])
Y = np.array([[6, 0], [2, 5]])
print(X, '\n')
print(Y)

[[1 2]
 [3 4]] 

[[6 0]
 [2 5]]


In [87]:
X * Y

array([[ 6,  0],
       [ 6, 20]])

In [88]:
np.dot(X, Y)

array([[10, 10],
       [26, 20]])

In [89]:
X.dot(Y)

array([[10, 10],
       [26, 20]])

In [90]:
Y.dot(X)

array([[ 6, 12],
       [17, 24]])

In [91]:
X @ Y

array([[10, 10],
       [26, 20]])

### Liczby pseudolosowe

In [92]:
np.random.seed(0)

In [93]:
np.random.randn()

1.764052345967664

In [94]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [95]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [99]:
np.random.rand()

0.3687251706609641

In [100]:
np.random.rand(10, 2)

array([[0.82099323, 0.09710128],
       [0.83794491, 0.09609841],
       [0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552],
       [0.73926358, 0.03918779],
       [0.28280696, 0.12019656],
       [0.2961402 , 0.11872772],
       [0.31798318, 0.41426299],
       [0.0641475 , 0.69247212],
       [0.56660145, 0.26538949]])

In [101]:
np.random.randint(10)

9

In [102]:
np.random.randint(10)

1

In [103]:
np.random.randint(low=10, high=101)

46

In [104]:
np.random.randint(low=10, high=101, size = 10)

array([20, 96, 53, 21, 12, 61, 90, 42, 64, 10])

In [105]:
np.random.choice([4, 2, 5, 7])

np.int64(5)

In [106]:
np.random.choice(['python', 'java', 'sql'])

np.str_('sql')

In [108]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.random.shuffle(data)
data

array([7, 9, 2, 1, 6, 5, 0, 4, 8, 3])

### Podstawowe funkcje numpy


In [110]:
np.exp(1)

np.float64(2.718281828459045)

In [111]:
np.sqrt(9)

np.float64(3.0)

In [112]:
np.all([2, 3, 1])

np.True_

In [116]:
np.all([2, 3, 0])

np.False_

In [117]:
np.any([0, 0, 0])

np.False_

In [118]:
np.any([0, 0, 1])

np.True_

In [119]:
bool(0)

False

In [121]:
A = np.random.randn(5)
A

array([-0.22686923,  0.81116027,  0.28779461, -0.53846816,  1.9084621 ])

In [122]:
np.argmax(A)

np.int64(4)

In [123]:
A[np.argmax(A)]

np.float64(1.9084621003056945)

In [124]:
A[np.argmin(A)]

np.float64(-0.5384681601851071)

In [125]:
np.argsort(A)

array([3, 0, 2, 1, 4])

In [126]:
np.max(A)

np.float64(1.9084621003056945)

In [127]:
np.min(A)

np.float64(-0.5384681601851071)

In [128]:
np.median(A)

np.float64(0.2877946131063574)

In [129]:
np.std(A)

np.float64(0.86244625739517)

In [130]:
np.average(A)

np.float64(0.44841591929247643)

### Indeksowanie

In [4]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [133]:
#A[idx], A[start:stop], A[:stop], A[start:]

In [5]:
A[2]

np.int64(2)

In [6]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [7]:
A[:2]

array([0, 1])

In [9]:
A[[0,2]]

array([0, 2])

In [10]:
A[10:15]

array([10, 11, 12, 13, 14])

In [12]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
A[0]

array([0, 1, 2, 3, 4])

In [15]:
A[1]

array([5, 6, 7, 8, 9])

In [16]:
A[:, 0]

array([ 0,  5, 10, 15])

In [17]:
A[:, 1]

array([ 1,  6, 11, 16])

In [18]:
A[:, -1]

array([ 4,  9, 14, 19])

In [20]:
A[1, 3]

np.int64(8)

In [21]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [23]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
### Iteracje po tablicach

In [25]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [27]:
for row in A:
  print(row[0])

0
5
10
15


In [28]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [29]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [30]:
A.shape

(4, 5)

In [36]:
A.reshape(5,4)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
A.T
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
### Maski logiczne

In [40]:
A = np.arange(start = -10, stop = 10, step = 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [41]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [44]:
np.bitwise_and(A>-5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [45]:
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [46]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [47]:
A[np.bitwise_or(A<-5, A>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])