<a href="https://colab.research.google.com/github/DGluszyk/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Norma wektora

In [6]:
pip install numpy

In [7]:

import numpy as np

In [11]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [12]:
np.linalg.norm(v1)

np.float64(4.123105625617661)

### Norma euklidesowa

In [14]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

np.float64(19.209372712298546)

## Odległość dwóch punktów w płaszczyźnie w przesytrzeni

In [15]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p-q)

np.float64(5.0)

In [16]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p-q)

np.float64(5.0990195135927845)

### Mnożenie macierzy

In [17]:
X = np.array([[5, 3], [3, 9]])

In [19]:
Y = np.array([[1], [-1]])

print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [21]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [23]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])
print(X, '\n')
print(Y)


[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [24]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

### Wyznacznik, macierz jednostkowa, odwrotna i transponowana

In [27]:
A = np.array([[2, 3],
              [3, 1]])

Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

round(np.linalg.det(A))

-7

In [39]:
A = np.array([[2, 5],
              [3, 1]])

np.trace(A)

np.int64(3)

In [29]:
np.eye(5, dtype='int')


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
A

array([[2, 3],
       [3, 1]])

In [32]:
B = np.linalg.inv(A)
B

array([[-0.14285714,  0.42857143],
       [ 0.42857143, -0.28571429]])

In [34]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[ 1., -0.],
       [ 0.,  1.]])

In [35]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [36]:
np.transpose(A)

array([[2, 3],
       [3, 1]])

In [37]:
A

array([[2, 3],
       [3, 1]])

In [40]:
A.T

array([[2, 3],
       [5, 1]])

### Rozwiązywanie układów równań

In [41]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [43]:
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [44]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [45]:
X.shape

(2, 1)